import os
from services.questionnaire import remind_to_complete_questionnaire
from model.patient_management.patient_account import handle_account_management
from model.patient_management.health_wellbeing import handle_health_wellbeing
from model.patient_management.appointment import *
from services.comment import comment